FROM pytorch/pytorch:2.8.0-cuda12.8-cudnn-runtime

WORKDIR /app

COPY runtime/api-requirements.txt runtime/api-requirements.txt
RUN pip install --no-cache-dir -r runtime/api-requirements.txt
RUN python -m pip install ninja && python -m pip install --no-build-isolation -v flash-attn

COPY .. .

ENV SENTIMENT_CONFIG_PATH=/app/config.yaml

CMD ["python", "-m", "runtime.app"]
